# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "EASYTRAVELDEPLOYMENT= $EASYTRAVELDEPLOYMENT"
  displayName: 'Run a one-line script'
- bash: 
- task: Bash@3
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)set_deployment_var.sh'
- script: |
    echo "EASYTRAVELDEPLOYMENT now= $EASYTRAVELDEPLOYMENT"
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      **/*
      !.git/**/*
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: MyBuildOutputs
