# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: "0 * * * *"
  displayName: Hourly build
  branches:
    include:
    - main

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "EASYTRAVELDEPLOYMENT= $EASYTRAVELDEPLOYMENT"
    ls '$(System.DefaultWorkingDirectory)'
    pwd
    env
  displayName: 'Show files build and vars'
- task: Bash@3
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/set_deployment_var.sh'
- script: |
    echo "EASYTRAVELDEPLOYMENT= $EASYTRAVELDEPLOYMENT"
    ls
    ls '$(System.DefaultWorkingDirectory)'
  displayName: 'Check deployment vars'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      **/*
      !.git/**/*
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: MyBuildOutputs
